Feature/locker-register branch
Lit-innosence/tus_yuurikai_system pull request #10
Opened 2024-08-18 03:21 UTC by Lit-innosence

2024-08-18 18:56 UTC, Lit-innosence commented
## Request処理
## 概要
- ロッカー登録用のパスを追加
- データベースにlocker、assignment_recordを追加
- student_pairリレーションからstudent_idを元にpair_idを検索する処理を追加
- assignment_recordへのinsert処理を追加

## テスト状態
- swagger-ui上でassignment_recordへの追加が行われていることを確認

## 要望
コードレビュー

- lockerへの追加処理を作成していないため、自力でINSERT文を打つ必要がある。
- upsert処理、その他同一内容が追加される場合の処理などはこれから実装する。

2024-08-19 02:59 UTC, Dot-P requested changes
## コードレビュー
変数、関数名については問題ありません。
具体的な処理に対していくつか疑問点があるので回答いただければと思います。

2024-08-19 02:59 UTC, Dot-P commented on src/main.rs
> +    let user_pair = match db_connector::get_studentpair_by_student_id(&mut conn, &assignment.student_id) {
select -> insert は冗長ではないかを確認したい
join -> select を一つの関数にまとめる形ではだめなのか

2024-08-19 02:59 UTC, Dot-P commented on src/main.rs
> +    let user_pair = match db_connector::get_studentpair_by_student_id(&mut conn, &assignment.student_id) {
yearが引数にないので、複数のレコードが抽出されないか

2024-08-19 02:59 UTC, Dot-P commented on src/db_connector.rs
> +        .filter(student_pair::student_id1.eq(student_id))
student_idは1と2があり、どちらがクエリとしてくるのか分からないのではないか

2024-08-19 02:59 UTC, Dot-P commented on migrations/2024-08-18-115327_create_locker/up.sql
> +-- Your SQL goes here
lockerのinsert処理はdieselのup.sqlでは行えないという結論でとらえてよいか。
もし、そうであれば代替手段を考える必要がある。
結局、本番環境での構成で必要になるので、何かしらの手段があるのかをリサーチしてほしい。

2024-08-19 03:04 UTC, Dot-P commented
また、ユニットテストは行いませんが、最終的には結合テストを行っていただきたいです。
想定としては httpリクエスト (入力) に対して正しい httpレスポンス が返ってくるのかをテストしたいと思っています。
Rustでどう書くのかのリサーチも含めてお願いしたいです。
テストを書くときは、データベースの初期化を行うことで冪等性を保証してください。
(体系的な方法なので詳しくは調べると出てくると思います。)

2024-08-19 04:26 UTC, Lit-innosence commented on src/main.rs
> +    let user_pair = match db_connector::get_studentpair_by_student_id(&mut conn, &assignment.student_id) {
joinはstudent_pairとlockerをjoinするという意味でしょうか。
結合方法や結合条件はどのようになるかなど教えていただきたいです。

2024-08-19 04:27 UTC, Lit-innosence commented on src/main.rs
> +    let user_pair = match db_connector::get_studentpair_by_student_id(&mut conn, &assignment.student_id) {
yearを引数に含め、student_idに加えyearも合致するタプルを抽出するように変更しました。

2024-08-19 04:27 UTC, Lit-innosence commented on src/db_connector.rs
> +        .filter(student_pair::student_id1.eq(student_id))
確かにstudent_pairには2つstudent_idがありますが、クエリとしてくるstudent_idはmain_userのものを想定しています。

2024-08-19 04:27 UTC, Lit-innosence commented on migrations/2024-08-18-115327_create_locker/up.sql
> +-- Your SQL goes here
記載するのを失念していましたが、リサーチした範囲ではマイグレーションツールでデータベースの初期状態を形成する方法を見つけられませんでした。
代替手段をリサーチ中です。

2024-08-19 04:39 UTC, Dot-P commented on src/main.rs
> +    let user_pair = match db_connector::get_studentpair_by_student_id(&mut conn, &assignment.student_id) {
- そもそもどちらの方法がよいのかを考える必要があるので良し悪しに対して意見がほしい
- 結合条件は、student_idがstudent_id1かstudent_id2に等しいかどうかでよい気がします
- 基本的にORMapperでは結合用のメソッドが用意されているはずですが、dieselに結合できる関数が用意されているかわからないのでドキュメントを読む必要がある

2024-08-19 04:42 UTC, Dot-P commented on src/main.rs
> +    let user_pair = match db_connector::get_studentpair_by_student_id(&mut conn, &assignment.student_id) {
select -> insert の方が優れていると判断できれば下二つの項目については考える必要がないので、一番上の項目について特に意見をいただきたいです。

2024-08-19 04:52 UTC, Dot-P commented on src/db_connector.rs
> +        .filter(student_pair::student_id1.eq(student_id))
確かにどちらにするか開発上で統一すればよい気がするので、student_1をmain_userのものと考えます。修正は必要ありません。

2024-08-19 05:22 UTC, Lit-innosence commented on src/main.rs
> +    let user_pair = match db_connector::get_studentpair_by_student_id(&mut conn, &assignment.student_id) {
そもそもassignment_recordには初期状態としてタプルが挿入されていないため、join -> select でロッカー登録を実装する方法がとれないと思われます。
現状select -> insert以外でロッカー登録を実装する方法が思い浮かばないため、この方法がよいと考えます。

2024-08-19 05:48 UTC, Dot-P requested changes

2024-08-19 05:48 UTC, Dot-P commented on migrations/2024-08-18-115712_create_assignment_record/up.sql
> +    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
deleted_atでは？

2024-08-19 05:49 UTC, Dot-P commented on src/main.rs
> +    let user_pair = match db_connector::get_studentpair_by_student_id(&mut conn, &assignment.student_id) {
ロッカー検索と勘違いしていました。
失礼しました。問題ないです。

2024-08-22 15:11 UTC, Dot-P commented on migrations/2024-08-18-115327_create_locker/up.sql
> +-- Your SQL goes here
mysqlではないのですが、こんな感じでいけません？
mysql -h 127.0.0.1 -u docker sampledb -p < insertData.sql

2024-08-26 13:01 UTC, Lit-innosence commented on migrations/2024-08-18-115327_create_locker/up.sql
> +-- Your SQL goes here
sql文ではありますが、同じような処理をCOPYで行えるようです。
# COPY locker FROM '[ファイルパス(絶対パス)]';
参考文献：https://www.postgresql.jp/document/16/html/sql-copy.html

本番環境で行う方法は今のところわかりませんが、ローカルではこの方法でデータを格納できそうです。

2024-08-26 13:02 UTC, Lit-innosence commented on migrations/2024-08-18-115712_create_assignment_record/up.sql
> +    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
deleted_atに変更しました。

2024-08-27 13:35 UTC, Dot-P commented on migrations/2024-08-18-115327_create_locker/up.sql
> +-- Your SQL goes here
どちらも本番で使えそうな気がします。
記述面では、後者のほうが楽だと思うので、とりあえずそれで進めてください。
使用したコマンドとファイルはどこかに残しておくと助かります。

2024-08-28 14:14 UTC, Dot-P approved these changes
コードの変更が確認されました。

2024-08-28 16:03 UTC, Lit-innosence commented
conflictは解消しました。
しかし、mail-auth関連の関数が消えてしまいコンパイルが通りません。
ローカルでの確認はmerge後でも大丈夫でしょうか...?

2024-08-29 02:22 UTC, Dot-P commented
ローカルでの確認はmerge後でも大丈夫です

2024-08-29 06:50 UTC, merged