Feature/mail-auth
Lit-innosence/tus_yuurikai_system pull request #11
Opened 2024-08-18 03:22 UTC by Dot-P

2024-08-18 07:01 UTC, Dot-P commented
![Screenshot from 2024-08-18 16-00-36](https://github.com/user-attachments/assets/c18af548-6974-40fe-a793-353c18903d1b)
Gmail->Gmailはできました。

2024-08-18 08:24 UTC, Dot-P commented
## メール送信システム
## 概要
- 自分自身のメールアドレスにメールを送れるようにgmailのsmtpサーバーに情報を送る[[参考資料]](https://zenn.dev/daddy_yukio/articles/8c6a15fc09548a)
- どんな環境変数を使えばよいかは .env.sample を参照するとよい
- アプリパスワードは自分で取得する必要がある(Googleアカウントの二段階認証が必須)
## テスト状態
Gmailから{Outlook, Gmail}に情報を送信できていることを確認。
## 要望
コードレビュー
## 今後のタスク
トークンの生成、一時データベースの作成

2024-08-18 11:03 UTC, Lit-innosence reviewed
Gmailを用いて送信できていることが確認できました。
問題ないと思います。

2024-08-20 03:19 UTC, Dot-P commented
## トークンの生成とデータベースへの登録
## 概要
- main_userとco_userの両方にトークンを発行し、メールを送信
- トークン内容と学生情報はauthテーブルに格納
- 乱数生成は、暗号論的擬似乱数生成器（CSPRNG) を使用
- 乱数は 0-9, a-z, A-Zの16文字で一様分布に従う
## テスト状態
- sender_addressからPOSTで指定した学籍番号の学校メールアドレスに認証URLが届いていることを確認
- データベースにトークンと学生情報が登録されていることを確認
## 要望
コードレビュー、ローカルでの確認
- 一通りの処理として完成させたので、ローカルでテストをお願いします
- 結合テストは行えない形式になっているので、全体が完成したときの運用テストや負荷テストの対象とします
- ローカルでテストする際は、POSTで指定した学籍番号にメールが届くことに注意してください (自分の学籍番号のみにしてください)
- とりあえず動く形にしたいので、暗号的強度は考えていません。ブラッシュアップとしてセキュリティを高めるコードに修正するときに行います。
## 参考事項
トークン長は16にしてあります。これは衝突可能性が十分低いことに基づいています。
![Screenshot from 2024-08-20 00-38-19](https://github.com/user-attachments/assets/828dd035-303e-4e2b-b566-266380e13952)

2024-08-27 03:16 UTC, Lit-innosence requested changes
ローカルでのメール送信が確認できました。
変数名や処理内容は問題ないと思いますが、ローカルでテストするにあたってdiesel cliに関して少し問題が生じたのでその詳細と改善案の提案をしました。確認お願いします。

2024-08-27 03:16 UTC, Lit-innosence commented on src/schema.rs
互いに新しくデータベースを追加していると、ブランチを切り替えるにあたってdiesel cliがうまく動きません（migrationsに現在のデータベースのup.sql、down.sqlがないのでrevertができなく、データベースを更新できない）。
conflictの可能性を排除するためにも、コミットないしマージ前にdiesel cliでrevertを行い、schema.rsおよびデータベースが空の状態にしておく方がよいと思われます。

2024-08-27 13:23 UTC, Dot-P commented on src/schema.rs
おそらく言っていることは、自分の手元にはあるテーブルが存在するのだけども、レビューするべきブランチにはないので、そこでエラーが起きるという内容だと解釈しています。

conflictがおきるというのが、gitではなく、diesel上のことを指していると思うのですが、「データベースが空の状態にしておく方がよい」というのは妥当です。私の伝え忘れです。

schema.rsは問題ない気がするので、詳細を教えてください。

2024-08-27 13:25 UTC, Dot-P commented on src/schema.rs
また、これらは面倒なので、いずれは自動化したいと思っています。
Github Actionsの導入、Dockerコンテナの作成で解決できると思うのですが、知見がないので、今回はスルーします。
いずれ導入はしようとおもいますが、とりあえず、開発が落ち着いてからにしたいと思っています。

2024-08-27 13:49 UTC, Lit-innosence commented on src/schema.rs
問題についての解釈はあっています。
conflictについてはgitのことですが、杞憂かもしれません。
詳細は次の通りです。

schema.rsの内容自体に問題はありませんが、「schema.rsに内容が記載されている状態（=データベースにテーブルが存在する状態）」でコミットやマージを行うと、ブランチを切り替える際にrevertをし「schema.rsに内容が記載されていない状態（=データベースが空の状態）」にすると変更があるとみなされてしまうという問題があります。
この状態だと、ブランチを切り替える際に手間がかかってしまうため、「schema.rsに内容が記載されていない状態（=データベースが空の状態）」でコミットないしマージを行う形に統一したほうがよいかと考えています。

2024-08-28 05:01 UTC, Dot-P commented on src/schema.rs
schema.rsについて理解しました。
対応としては.gitignoreに追加するのが適切であると思われます。
ブランチを切るごとに自動生成する方向でお願いします。
その修正は今行います。

2024-08-28 05:23 UTC, Lit-innosence commented on src/schema.rs
わかりました。
他に問題点等ありませんのでresolveします。

2024-08-28 05:24 UTC, Lit-innosence approved these changes

2024-08-28 05:36 UTC, merged