Refactor/mail-auth
Lit-innosence/tus_yuurikai_system pull request #12
Opened 2024-09-02 10:53 UTC by Dot-P

2024-09-02 11:02 UTC, Dot-P commented
## メール認証部分のリファクタ
## 概要
- "/mail-auth", "user-register"を消去
- "/token-gen"(post), "/main-auth"(get), "/co-auth"(get)を追加
-  処理の流れは仕様書(Notion)を参考
## テスト状態
目視による確認を行った
- 生成していたtokenが{main, co}の認証で有効かどうか
- 誤ったtokenを入力したときに401を返すかどうか
## 要望
- コードレビュー
- 以下の質問の回答
## 質問
- 結合テストを行うべきかどうか
- 行うとしたらどのように行うべきか、行わないならどのように品質を保証するのか

2024-09-03 08:49 UTC, Lit-innosence requested changes
## コードレビュー
処理については問題ないと思います。

2024-09-03 08:49 UTC, Lit-innosence commented on src/adapters/repository.rs
> +    }
関数名をget_by_tokenに変更するべきだと思います。
今後、created_atなどで取得するケースが出てくるかもしれないのでわかりやすくするために。

2024-09-03 08:49 UTC, Lit-innosence commented
## 結合テストについて
token周りが不安なので、結合テストは行うべきだと思います。
その場合、tokenの品質を保証するため、メール送信周りの処理を省く形で結合テストを記述するべきであるかと。

2024-09-03 12:19 UTC, Dot-P commented
メール送信周りを除きながらトークンのチェックをするのが非常に困難だと思っています。
具体的には、
1. トークンがランダムであるのでテストを組みづらい(.eqなどが使えない)
2. メール送信部分を取り除くと、テストカバレッジが大幅に減少する

つきましては、もう少し具体的な内容について説明をお願いしたいです。

2024-09-03 13:02 UTC, Lit-innosence approved these changes

2024-09-03 13:06 UTC, merged