Feature/locker-user-search
Lit-innosence/tus_yuurikai_system pull request #19
Opened 2024-10-05 00:30 UTC by Lit-innosence

2024-10-07 12:07 UTC, Lit-innosence commented
## 概要
- ロッカー利用者検索用のパス/user-searchを追加。
- studentテーブルにget_by_id、get_by_nameを追加。
- student_pairのget_by_idに渡す引数をAssignmentInfoからpair_idに変更
- assignment_recordテーブルにget処理を追加。現状、year、pair_idが必須。floorはオプションとして選べる。
- /user-searchの結合テストを正常動作項目のみ追加

## テスト状態
- 結合テストで正常動作項目が成功することを確認

## 今後の流れ
- 結合テストに項目を追加し、逐一修正を加えていく方針で行こうと思っています。
- レスポンスのhttpステータスが不自然なのは一時的なものです。結合テスト時に各エラーレスポンスが判別でき、かつ妥当なレスポンスになるよう改善していきます。

2024-10-10 12:23 UTC, Lit-innosence commented
## 概要
- ロジック面の改善
- 名前が空白の場合に対応、それに伴うテスト項目の追加

## テスト状態
- テストが正常に終了することを確認

## 要望
- コードレビュー、ローカルでの確認

2024-10-10 15:33 UTC, Dot-P requested changes

2024-10-10 15:33 UTC, Dot-P commented on src/adapters/controller.rs
> +        Err(_) => return Err(Status::BadGateway),
ステータスコードを修正することを忘れています。

2024-10-10 15:33 UTC, Dot-P commented
ローカルでの確認は問題ありませんでした。

2024-10-11 11:57 UTC, Lit-innosence commented on src/adapters/controller.rs
> +        Err(_) => return Err(Status::BadGateway),
修正しました。

2024-10-11 11:58 UTC, Lit-innosence commented
- lockerテーブルのstatusをoccupiedに変更
- レスポンスを統一
- auth処理のメッセージで送られるURLにクエリパラメータmethodを追加

上記の修正を加えました

2024-10-12 11:33 UTC, Dot-P approved these changes

2024-10-12 11:35 UTC, Dot-P commented
マージしていいかわからんので、もしいいのであれば自身でマージして貰えると助かります

2024-10-13 15:15 UTC, merged