Feature/Frontend-circle-select
Lit-innosence/tus_yuurikai_system pull request #33
Opened 2024-11-03 03:10 UTC by Dot-P

2024-11-03 03:13 UTC, Dot-P commented
## 概要
- サークルの遷移画面の追加
- リダイレクト用のページを追加
## テスト状態
ローカルで動くことを確認
## 要望
コードレビュー、ローカルテスト、マージ
## 今後の展望
マージ後、circleの各ページのフロントエンドを作成します。

2024-11-03 06:01 UTC, Lit-innosence requested changes

2024-11-03 06:01 UTC, Lit-innosence commented on frontend/src/routes/component/Redirect.tsx
> +                break;
同じくOnedriveに変更お願いします

2024-11-03 11:14 UTC, Dot-P commented on frontend/src/routes/circle/CircleSelect.tsx
> +    { title: '公開資料閲覧', route: '/redirect/google' }, // Google Drive Link
新規登録と公開資料閲覧は両方同じURLでいいの？

2024-11-04 00:14 UTC, Lit-innosence commented on frontend/src/routes/circle/CircleSelect.tsx
> +    { title: '公開資料閲覧', route: '/redirect/google' }, // Google Drive Link
新規登録はgoogleform、公開資料はOneDriveでお願い
紛らわしくてすまんね

2024-11-05 02:18 UTC, Dot-P commented on frontend/src/routes/circle/CircleSelect.tsx
> +    { title: '公開資料閲覧', route: '/redirect/google' }, // Google Drive Link
googleformはまだ存在しないから新規登録の方はまだモックのままでよいっていうこと？

2024-11-05 02:21 UTC, Lit-innosence commented on frontend/src/routes/circle/CircleSelect.tsx
> +    { title: '公開資料閲覧', route: '/redirect/google' }, // Google Drive Link
YES．新規登録のGoogleFormURLは準備でき次第変更する形でお願いします。

2024-11-05 10:44 UTC, Dot-P commented
URLが長くなったときに真ん中に位置しなかったのでその部分も修正しておきました。

2024-11-05 11:44 UTC, Lit-innosence commented
確認できたのでマージします

2024-11-05 11:44 UTC, Lit-innosence approved these changes

2024-11-05 11:44 UTC, merged