Fix/Usersearch and auth process api bugs
Lit-innosence/tus_yuurikai_system pull request #34
Opened 2024-11-03 04:45 UTC by Lit-innosence

2024-11-03 05:46 UTC, Lit-innosence commented
## 概要
- ロッカー空き状態検索およびロッカー利用者検索APIのレスポンスデータをcamelCaseに変更
- 認証検証APIに使われるauthレコードの削除処理をロッカー登録の最後に移動
- 上記修正に伴いテストコードを修正
- swagger-uiおよびテスト時のusersearchのルーティングを/api/admin/locker/usersearchに修正し忘れていたためルーティングに/lockerを追加

## 要望
- ローカルでの確認
  - 特に、フロントエンドでロッカー登録をするまでauthレコードが削除されていないことを確認してほしいです
- `cargo test -- --test-threads=1`が正常に終了することを確認

確認、コードレビュー共によかったらマージをお願いします

2024-11-03 11:35 UTC, Dot-P requested changes

2024-11-03 11:35 UTC, Dot-P commented on src/adapters/controller.rs
> +    /*
不要なら消す

2024-11-03 12:01 UTC, Dot-P commented
`cargo test -- --test-threads=1`

これで失敗します。以下が失敗するテストです。

```
Running tests/availability.rs (target/debug/deps/availability-c95ef186945653d5)

running 2 tests
test floor_is_not_requested ... FAILED
test normal ... FAILED
```
左右 (出力と期待される結果) の差分が一致しないです。
おそらくpsqlにcsvをコピーする際、idの順でソートされるとは限らないのが問題であると考えています。expected_resultをソート順にすることを検討、もしくは他の代替案の提示をお願いします。

2024-11-03 12:12 UTC, Dot-P commented
それ以外のローカルでの動作は問題ありません

2024-11-03 16:03 UTC, Lit-innosence commented on src/adapters/controller.rs
> +    /*
消去しました

2024-11-05 02:03 UTC, Dot-P approved these changes
変更が確認できました。
マージします。

2024-11-05 02:03 UTC, merged