Feat/Backend-locker-reset
Lit-innosence/tus_yuurikai_system pull request #36
Opened 2024-11-07 08:51 UTC by Lit-innosence

2024-11-07 08:55 UTC, Lit-innosence commented
## 概要
- バックエンドのロッカーリセットAPIを作成、ルーティングに追加
- APIの結合テストを作成

## テスト状態
- 結合テストが正常に終了することを確認

## 要望
- コードレビュー、ローカルでのテスト
- テスト時は`cargo test --test lockerreset -- --test-threads=1`を用いてください

2024-11-07 09:08 UTC, Lit-innosence commented
### 追記
- パスワードはNotionの共有ファイルに記載しています。
- テスト項目はNotionにまとめました。これを追加したほうがいいんじゃないか、などあれば意見ください。
- マージ後は団体情報登録APIに移ります。

2024-11-07 14:01 UTC, Dot-P requested changes
コードレビューをしました。

2024-11-07 14:01 UTC, Dot-P commented on .env.sample
> +LOCKER_RESET_PASSWORD=""
ロッカーのパスワードは管理者のパスワードと同じではだめなのですか？

2024-11-07 14:10 UTC, Dot-P commented
テストに関しては、値空間が広いので、正常系の条件が正しいことを保証できそうなテスト(今の正常系を合体すればOK)+モンキーテストを行うといい気がします。これらをそれぞれ関数にし、正常系は２つのテストを組むと良い気がします。

モンキーテストに関してはそこまで深く作り込まずにランダムにいくつの条件とチェック対象を決めておけばOKです。

2024-11-07 14:18 UTC, Dot-P commented on tests/lockerreset.rs
> +    sleep(time::Duration::from_secs(62));
ここまで時間を長くする意味はなくないか？

2024-11-07 15:15 UTC, Lit-innosence commented on src/usecase/locker.rs
> +        // out-of-workのロッカーを取得
確かにそうですね...あまり考えずに実装していました、申し訳ない。

2024-11-07 15:15 UTC, Lit-innosence commented on tests/lockerreset.rs
> +    assert_eq!(status, String::from("vacant"));
アドバイスいただけた通りに改善してみます。

2024-11-08 03:41 UTC, Dot-P commented on .env.sample
> +LOCKER_RESET_PASSWORD=""
了解です。それなら別のパスワードにしましょう。

2024-11-09 04:17 UTC, Lit-innosence commented
### 修正点
- ロッカーリセットAPIのロジックを変更
  - statusがoccupiedのロッカーをvacantに更新するようになりました
- repositoryのlockerに関する関数を変更
  - 既存のupdate_status関数はupdate_status_by_idになりました。
  - 新たにupdate_status関数を作成しました。指定したfloorとstatusに当てはまるロッカーを新しいstatusに更新します。
- テストを改善しました
  - jwt_is_not_validの項目に時間がかからないようになりました。
  - 正常系のテストを一項目にまとめ、新たにモンキーテストを追加しました。

2024-11-09 04:17 UTC, Lit-innosence commented
修正点についてコードレビューとローカルテストをお願いします。

2024-11-09 08:23 UTC, Dot-P approved these changes
問題ないです。

2024-11-09 08:24 UTC, Dot-P commented
マージをお願いします。

2024-11-09 08:31 UTC, merged