Feat/Add-update-token-gen-API
Lit-innosence/tus_yuurikai_system pull request #41
Opened 2024-11-25 12:38 UTC by Lit-innosence

2024-11-27 12:51 UTC, Lit-innosence commented
## 概要
- 団体情報更新認証APIを作成
団体情報更新の際、Form入力後のメール認証プロセスにおいて使用するtokenの作成、auth関連のDBへの情報の登録、新代表者へのメールの送信を行います。

## テスト状態
- swagger-ui上で実行し、メールが送られてくることを目視で確認

## 要望
- コードレビュー、ローカルでのテスト

団体のメール認証の流れは次の通りです。
団体情報更新と団体登録の認証は、入口のAPIのみ別とし、tokenを確認する認証APIは共通となります。
```mermaid
graph LR;
    A("団体情報更新認証API") --> B("代表者認証API");
    C("団体登録認証API") --> B("代表者認証API");
    B("代表者認証API") --> D("副代表者認証API");
    D("副代表者認証API") --> E("団体情報更新");
    D("副代表者認証API") --> F("団体情報登録");
```

2024-11-27 13:51 UTC, Dot-P commented
リンクが以下のように返ってきています。
昨日の定例で修正していた気がするので一部pushし忘れていませんか？

http://localhost:8000?/*フロントエンドのURL*/method=1&token=pR0TqbCAU8w0mSAb&id=C00000

2024-11-27 14:05 UTC, Dot-P requested changes
コードレビューを2点しました

2024-11-27 14:05 UTC, Dot-P commented on src/adapters/controller/circle.rs
> +    let content = format!("{}{} 様\n\n以下のURLにアクセスして認証を完了してください。\n{}?/*フロントエンドのURL*/method=1&token={}&id={}", main_user.family_name, main_user.given_name, app_url, token, data.organization_id);
フロントエンドのURLになっている

2024-11-28 10:58 UTC, Lit-innosence commented on src/adapters/controller/circle.rs
> +    let user_address = format!("{}", main_user.email);
変更しました

2024-11-28 11:00 UTC, Lit-innosence commented on src/adapters/controller/circle.rs
> +    let content = format!("{}{} 様\n\n以下のURLにアクセスして認証を完了してください。\n{}?/*フロントエンドのURL*/method=1&token={}&id={}", main_user.family_name, main_user.given_name, app_url, token, data.organization_id);
具体的なURLに変更しました

2024-11-28 11:10 UTC, Dot-P approved these changes
正しく動いていることが確認できました。
マージのタイミングは任せます。

2024-11-29 08:01 UTC, Lit-innosence commented
## 概要
- 団体登録認証APIを作成
団体登録の際、Form入力後のメール認証プロセスにおいて使用するtokenの作成、auth関連のDBへの情報の登録、新代表者へのメールの送信を行います。

## テスト状態
- swagger-ui上で実行し、メールが送られてくることを目視で確認

## 要望
- コードレビュー、ローカルでのテスト

コードレビューとテスト共にOKだったらマージしてください。

2024-11-29 13:03 UTC, Dot-P requested changes
基本的に問題はありませんが、b_url -> b_doc などに名称変更をお願いします

2024-11-30 14:50 UTC, Lit-innosence commented on migrations/2024-11-21-141439_create_circle_auth_info/up.sql
> +    b_url TEXT NOT NULL,
*_urlとなっていたすべての箇所を*_docに変更しました

2024-11-30 15:21 UTC, Dot-P approved these changes
問題がなかったのでマージします

2024-11-30 15:21 UTC, merged