Feature/backend-circle-mail-auth
Lit-innosence/tus_yuurikai_system pull request #42
Opened 2024-12-02 14:09 UTC by Lit-innosence

2024-12-02 14:17 UTC, Lit-innosence commented
## 概要
- 団体代表者認証APIを作成
  - 団体登録、団体情報更新時の認証プロセスで使用します。
  - API内でtokenの検証、representativesデータベースに代表者の情報をupsert処理で追加します。
  - upsert処理ではemail、phone、updated_atが変更されます。
- 団体登録に使用する各データベースを追加

## テスト状態
swagger-ui上で実行しメールが送られてくることを目視で確認

## 要望
コードレビュー、ローカルでの確認
2回実行し、upsert処理が正常に動いていることも確認してください。
今後使用予定のDBもまとめて追加しているのでそちらのコードレビューもお願いします。

2025-01-06 06:41 UTC, Dot-P requested changes

2025-01-06 06:41 UTC, Dot-P commented on src/adapters/controller/circle.rs
>      let content = format!("{}{} 様\n\n以下のURLにアクセスして認証を完了してください。\n{}/circle/register/auth?method=1&token={}", main_user.family_name, main_user.given_name, app_url, token);
lockerのときmethodは0,1,2...の形じゃなかったっけ？
そうだとしたら0番がなくないか？？

2025-01-06 06:41 UTC, Dot-P commented on src/adapters/controller/circle.rs
> +        Some(id) => format!("{}{} 様\n\n以下のURLにアクセスして認証を完了してください。\n{}/circle/update/auth?method=2&token={}&id={}", co_user.family_name, co_user.given_name, app_url, auth.co_auth_token, id),
上記同様method確認

2025-01-06 06:41 UTC, Dot-P commented on src/adapters/controller/circle.rs
> +        None => format!("{}{} 様\n\n以下のURLにアクセスして認証を完了してください。\n{}/circle/register/auth?method=2&token={}", co_user.family_name, co_user.given_name, app_url, auth.co_auth_token),
上記同様method確認

2025-01-06 06:41 UTC, Dot-P commented on src/adapters/controller/circle.rs
> +        Some(id) => format!("{}{} 様\n\n以下のURLにアクセスして認証を完了してください。\n{}/circle/update/auth?method=2&token={}&id={}", co_user.family_name, co_user.given_name, app_url, auth.co_auth_token, id),
クエリパラメータのidって何を指すんだっけ？？

2025-01-06 07:36 UTC, Dot-P commented
usecase.rsのpub mod organization;でエラーを吐くんだけどこれは消したときの動作が動けばいいの？？
/*以下は消して修正したときの内容について*/
1回目のローカルでの確認では問題ありませんでした。二回目以降の動作確認は何をチェックすればいいのかがいまいちわからんのだが、token-genを二回実行したときにcircle_auth_infoの行が2行になればいいってこと？？

2025-01-06 14:25 UTC, Lit-innosence commented
usecase.rsの7行目は消して動作確認でお願いします。
確認してほしいのはcircle/main-authの団体認証APIで、1回目は動くかどうか、2回目はupsert処理が動いているかを確認してほしい。email、phoneについてはupsert処理が働くようになっているから、1回目の実行時と値を変えて実行した場合、データベースの値（email、phone、updated_at）が変わっているかどうかを確認してほしい。（emailは変更できなかったらphoneについてのみで大丈夫）

2025-01-07 02:21 UTC, Dot-P commented
どのテーブルに対してupsertを確認すればいいかがいまいち理解出来てない、、circle_auth_infoを確認するのでいいの？そうだとしたらupsertになってない気がする、、

2025-01-07 03:37 UTC, Lit-innosence commented
確認して欲しいテーブルはrepresentativesです
十分に伝えられてなくて申し訳ない…

2025-01-09 08:26 UTC, Dot-P approved these changes
レビューOK

2025-01-09 08:35 UTC, Dot-P commented
動作に問題ないです

2025-01-09 14:18 UTC, Lit-innosence commented
## 概要
- 団体副代表者認証APIを作成
  - 団体登録、団体情報更新時の認証プロセスで使用します。
  - API内でtokenの検証、認証phaseの検証を行い、representativesデータベースに副代表者の情報をupsert処理で追加します。
  - また、クエリパラメタに応じて団体情報更新、団体情報新規登録を行います。
- データベースの修正
  - organization_idをシーケンスに修正しました。

## テスト状態
swagger-ui上で実行しメールが送られてくることを目視で確認
DBに情報が正しく実装されていることを目視で確認

## 要望
- コードレビュー、ローカルでの確認
  - 2回実行して、organizationに登録されているレコードのorganization_idがシーケンスになっているかの確認をお願いします。
  - また、登録完了メールが代表宛に正しく送信されているかの確認をお願いします。

2025-01-10 02:55 UTC, Dot-P commented
コードレビュー問題なし

2025-01-10 03:11 UTC, Dot-P commented
本来なら一致するidが存在しない場合、[/api/circle/update/token-gen]はエラーを返すべきですが、メールを送ってしまっているのでセキュリティ項目にて修正するようにしてください。

2025-01-10 03:12 UTC, Dot-P commented
>   2回実行して、organizationに登録されているレコードのorganization_idがシーケンスになっているかの確認をお願いします。また、登録完了メールが代表宛に正しく送信されているかの確認をお願いします。

問題ありません。

2025-01-10 03:15 UTC, Dot-P commented
ただし、2回実行したときorganizationにorganization_nameが空の新しい行ができてしまっている気がします。
![image](https://github.com/user-attachments/assets/cb2810aa-5ab3-46fc-b75e-8f2900aa2de7)

2025-01-10 04:52 UTC, Lit-innosence commented
こっちだとその現象が確認できなかったんだけど、原因になってそうな箇所はありそう？

2025-01-10 06:58 UTC, Dot-P commented
実行はregister操作2回+update操作2回でやってた
途中で
> 本来なら一致するidが存在しない場合、[/api/circle/update/token-gen]はエラーを返すべきですが、メールを送ってしまっているのでセキュリティ項目にて修正するようにしてください。

これをしたからこれが悪さしている可能性もある気がする

2025-01-10 12:20 UTC, merged