Feature/decode-json
Lit-innosence/tus_yuurikai_system pull request #6
Opened 2024-08-07 15:31 UTC by Lit-innosence

2024-08-11 14:33 UTC, Lit-innosence commented
## json形式案1(フォーム)
```json
{
    "data": {
        "student1": {
            "student_id": "4622999",
            "name": "山田　太郎",
        }.
        "student2": {
            "student_id": "4623000",
            "name": "山田　次郎",
        }
    }
}
```
### 概要
- 利用者2人のオブジェクトにそれぞれ学籍番号、名前をプロパティとして格納する。
- フォームの入力内容とは別の情報を併記するためにフォームの入力内容をdataオブジェクトのプロパティとする。

2024-08-11 15:31 UTC, Lit-innosence commented
##  json decode test
## 概要
- json形式のデコード用にserdeの導入および確認用パスとして"/test_json"を追加。
- 使用クレート：serde, serde_json
## テスト状態
- "/test_json"にて"hello world from json!"が返ってくることを目視で確認。
- [ドキュメント](http://127.0.0.1:8000/swagger-ui/)にてドキュメントが生成されていることを確認。
## 要望
- ローカルで正常に動くかを確認してほしい。
- json形式案1(フォーム)に問題がないか確認してほしい。

2024-08-12 00:21 UTC, Dot-P commented
> ## json形式案1(フォーム)
> ```json
> {
>     "data": {
>         "student1": {
>             "student_id": "4622999",
>             "name": "山田　太郎",
>         },
>         "student2": {
>             "student_id": "4623000",
>             "name": "山田　次郎",
>         }
>     }
> }
> ```
> 
> ### 概要
> * 利用者2人のオブジェクトにそれぞれ学籍番号、名前をプロパティとして格納する。
> * フォームの入力内容とは別の情報を併記するためにフォームの入力内容をdataオブジェクトのプロパティとする。

timestampはここで取得せずにバックエンドで追加するという認識であってる？

2024-08-12 00:41 UTC, Lit-innosence commented
timestampを取得することは考えてなかった。
timestampの用途としては
- ロッカー予約の先着順の処理
- ログ管理
が考えられるけど、前者はロッカー予約をどこで入力させるかによるし、後者もバックエンドで追加する形で問題ないと思うのでjsonから取得する理由は現状ないと思う。

2024-08-12 01:53 UTC, Dot-P commented
> 前者はロッカー予約をどこで入力させるかによるし、後者もバックエンドで追加する形で問題ないと思うのでjsonから取得する理由は現状ないと思う。

同意見です。timestampはjsonに追加しなくていいかも。

2024-08-12 01:56 UTC, Dot-P commented
あと、nameの姓と名を別にした方がいいと思うんだけどどう？
名前の間のスペースの処理 (全角、半角、スペースなし) が面倒くさいって感じてしまう。

2024-08-12 01:58 UTC, Dot-P commented
あと、上にコード修正の要望を記述しておいたので修正よろしくお願いします。
ざっとの記述になってるから、わからないところがあれば質問してくれると助かります。

2024-08-12 02:24 UTC, Dot-P requested changes
コード修正をお願いします

2024-08-12 02:27 UTC, Lit-innosence commented
> あと、nameの姓と名を別にした方がいいと思うんだけどどう？
> 名前の間のスペースの処理 (全角、半角、スペースなし) が面倒くさいって感じてしまう。

同意。改善した形式を以下載せます。

2024-08-12 02:32 UTC, Lit-innosence commented
## json形式案2（フォーム）
```json
{
    "data": {
        "student1": {
            "student_id": "4622999",
            "last_name": "山田",
            "first_name": "太郎",
        },
        "student2": {
            "student_id": "4623000",
            "last_name": "山田",
            "first_name": "次郎",
        }
    }
}
```
## 改善点
- 姓名の間に入るスペースの曖昧さを避けるため、姓名でプロパティを分けた。

2024-08-12 03:52 UTC, Lit-innosence commented
## 修正内容
- test_jsonがgetメソッドになっている

## 修正箇所
- test_jsonをpostメソッドに変更
- openapiドキュメントにexampleを追加

## テスト状態
- "/test_json"にて以下のjsonファイルをPOSTし、文字列が返ってくることを目視で確認。
```json
{
 "text": "hello world from json!"
}
```
- [ドキュメント](http://127.0.0.1:8000/swagger-ui)にてOpenAPIドキュメントが作成されていることを確認
- "try it out"にてexampleが正常に動くことを確認

2024-08-12 15:00 UTC, Dot-P commented
```
{
    "data": {
        "main_user": {
            "student_id": "4622999",
            "family_name": "山田",
            "given_name": "太郎",
        },
        "co_user": {
            "student_id": "4623000",
            "family_name": "山田",
            "given_name": "次郎",
        }
    }
}
```

2024-08-12 15:07 UTC, Dot-P approved these changes
ローカルでの動作が確認されたのでマージします。

2024-08-12 15:08 UTC, merged