Feature/user-register
Lit-innosence/tus_yuurikai_system pull request #8
Opened 2024-08-13 07:36 UTC by Dot-P

2024-08-13 08:13 UTC, Dot-P commented
## Requestの処理
## 概要
新しく「/locker/user-register」を追加。それに伴い、Request jsonを定義。
## テスト状態
swagger-ui上でrequest内の情報が正しく処理できているかを確認
## 要望
コードレビュー (コードの一部にすぎないので、テスト等は必要ありません)

2024-08-13 09:06 UTC, Lit-innosence requested changes

2024-08-13 09:06 UTC, Lit-innosence commented on src/main.rs
> +}
72，73行目でオブジェクト名とプロパティ名が一致しているのが紛らわしいので，メソッドの引数をrequest等に変更した方が良いと思います．

2024-08-13 09:21 UTC, Dot-P commented
## SQLを直接叩く方法
`psql -h localhost -p 5432 -d [任意のDB名]`

2024-08-13 09:33 UTC, Dot-P commented on src/main.rs
> +}
修正が完了しました。
問題がなければResolve conversationとApproveをお願いします。

2024-08-13 09:57 UTC, Dot-P commented
![Screenshot from 2024-08-13 18-56-49](https://github.com/user-attachments/assets/ea7e0f9f-5960-4f6c-89f9-01101256039a)
キー制約これでいいかな？

2024-08-13 11:15 UTC, Lit-innosence commented
> キー制約これでいいかな？ idを何によって定めるのかはリサーチしてまとめておきます。

大丈夫だと思います．
pair_idは例えば"0000-0000"のようなidをつけることを考えてSTRING型にしたっていう話だったよね

2024-08-13 13:43 UTC, Dot-P commented
autoincrementにするかUUIDにするか、その他にするか、後で考えればいいという結論になった気がする。
今考えると、ULIDが良きだと感じたんだが、どうだろうか。
パフォーマンス的にも劣ってなくて、同時挿入による異常も発生しにくいと思う。
参考資料: [ID生成方法についてあれこれ](https://zenn.dev/j5ik2o/articles/a085ab3e3d0f197f6559)

2024-08-13 14:05 UTC, Dot-P commented
update_atの自動更新はpostgresはサポートしていないみたいなので、rustで関数を作ろうと思ってます

2024-08-14 02:52 UTC, Dot-P commented
> ![Screenshot from 2024-08-13 18-56-49](https://private-user-images.githubusercontent.com/121503676/357365236-ea7e0f9f-5960-4f6c-89f9-01101256039a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1OTY1MTksIm5iZiI6MTcyMzU5NjIxOSwicGF0aCI6Ii8xMjE1MDM2NzYvMzU3MzY1MjM2LWVhN2UwZjlmLTU5NjAtNGY2Yy04OWY5LTAxMTAxMjU2MDM5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwMDQzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmNlNzk3MjkwMmE4YWRkM2Y4NmM0ZjdmMzdmY2QzN2JmZjMyNTZhZDIxZDc4YmFiNjc4MTA3MmU4N2Y1YjQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qc9cuv2fXOTgXdWCd236rnpONCik8VTGK1s708_vSvM)

nameはfamily_nameとgiven_nameに分けたほうがいいよね？

2024-08-14 06:13 UTC, Dot-P commented
## DB接続・Insert処理
## 概要
- migrationツールを導入し、dbのバージョン管理を行っている。
- ORMを導入し、models.rsに記述。DB操作を楽にしている。
- db_connection関数はデータベースの接続を、insert_studentはレコードの挿入を行っている。
- main関数にて、main_userとco_userをstudentテーブルにinsertしている。
## テスト状態
swagger-ui上でPOST処理を行い、その内容が正しくローカルDBに反映されているのかを目視で確認。
## 要望
**コードレビュー** 
- 自動生成されたコードは目を通さなくてよい
- SQLのcreateには変更があるので目を通してほしい
- 完成ではないので、同一人物の追加などのケースはまだ作成してない
- フィルターを使って特定のcommitに限定すると少し見やすいかも🦆
- 記述内容は理解し難いと思うので、変数名やコードの見やすさ、疑問の観点でレビューをしていただきたいです

2024-08-14 13:18 UTC, Lit-innosence commented
id選定とcreated_atの型について，現時点では異論ないです．
コード内の変数名は問題ないと思います．
細かいですがレビューしたので確認お願いします．
また，SQLのcreateが何を指すのかがわからなかったのでもう少し詳細にお願いします．

> フィルターを使って特定のcommitに限定すると少し見やすいかも🦆

すごく見やすくなった．ありがとう

2024-08-14 13:18 UTC, Lit-innosence commented on src/db_connector.rs
> +    .get_result(conn)
細かくて申し訳ないですが，インデントがなくスコープがわかりずらいのでインデントを入れてもらえると助かります．

2024-08-14 13:39 UTC, Dot-P commented
> また，SQLのcreateが何を指すのかがわからなかったのでもう少し詳細にお願いします.

create table ~ のファイル群のこと。migrationフォルダの中の up.sql (2つ) が該当します。

2024-08-15 01:05 UTC, Lit-innosence commented on src/db_connector.rs
> +    .get_result(conn)
24,25行目にインデントが入っていないです．
24,25行目のlet new_student ~ とdiesel::insert_into ~ の2文はinsert_intoメソッド内の処理だと思われるのですが，間違いないですか？

2024-08-15 01:05 UTC, Lit-innosence commented
> create table ~ のファイル群のこと。migrationフォルダの中の up.sql (2つ) が該当します。

ありがとうございます．
create文確認しました．問題ないと思います．

2024-08-15 02:26 UTC, Dot-P commented on src/db_connector.rs
> +    .get_result(conn)
> insert_intoメソッド内の処理

insert_studentのタイポだと思うんだけどあってる？
24,25行目の先頭にインテンデントをいれてほしいということで合ってるよね？

2024-08-15 02:27 UTC, Dot-P commented
メッセージテスト
動いたら消します。

2024-08-15 03:38 UTC, Dot-P commented
参考資料：[upsert処理-公式ドキュメント](https://docs.diesel.rs/master/diesel/upsert/index.html)

2024-08-15 03:46 UTC, Lit-innosence commented on src/db_connector.rs
> +    .get_result(conn)
> insert_studentのタイポだと思うんだけどあってる？
合ってます．更新が確認できたのでリゾルブします．

2024-08-15 05:15 UTC, Dot-P commented
## Upsert処理・ステータスコード・エラーハンドリング
## 概要
- すでにデータが登録されているとき([Issue参照](https://github.com/Lit-innosence/tus_yuurikai_system/issues/9#issue-2467313566))、updated_atが更新される。
- 成功時に201-Createdが、失敗時には Internal Serverエラーが発生
- db接続失敗時にもInternal Serverエラーが発生するように調整

## テスト状態
目視での確認。同じ学籍番号の情報がPOSTされたとき、updated_atが更新されていることを確認。
Student_Pairの処理を追加後、ユニットテストを行う予定。

## 要望
コードレビュー

参考資料：[upsert処理-公式ドキュメント](https://docs.diesel.rs/master/diesel/upsert/index.html)
参考資料：[ステータスコード-公式ドキュメント](https://api.rocket.rs/v0.4/rocket/http/struct.Status)

2024-08-16 04:55 UTC, Dot-P commented
## student_pairのInsert処理
## 概要
- student_pairテーブルにデータを挿入できるように調整
- コードステータスはstudentのときと同じ
## テスト状態
swagger-ui上でPOST処理を行い、その内容が正しくローカルDBに反映されているのかを目視で確認。
## 要望
コードレビュー
- 構成変更前の状態として適切かどうかを判断してほしい
- ユニットテストを行う予定でしたが構成変更の関係で変更後にずらします

2024-08-16 17:35 UTC, Lit-innosence approved these changes

2024-08-16 17:41 UTC, Lit-innosence commented
上記コードレビューは確認と質問なのでコードの変更は必要ありません．
構成変更によって既存のデータベースやORM処理に影響が及ぶ部分がないため，構成変更へ移って問題ない状態だと判断します．

2024-08-17 01:52 UTC, Dot-P commented on src/db_connector.rs
>              .get_result(conn)
正しいです

2024-08-17 02:01 UTC, Dot-P commented on src/main.rs
> +}
> 82~98行目の処理はメール認証APIに移動，一時データベースへの保存処理を追加という処理の分け方の認識で間違いないでしょうか．

より正確にいうと、83、89行目は"/user-register"に残します。その他はすべてメール認証APIに移動します。
ただし、エラーを出したままマージしたくないので、現在の処理は"/mail-auth"?にコピーしておき、"/user-register"を先に完成させマージしようと思っています。

2024-08-17 02:12 UTC, Dot-P commented
構成変更に移ろうと思ったのですが、メール認証を完成させる必要があります。
メール認証に必要な情報が何か分からない、一時データベースに何が入るか分からないといった問題を抱えていて、データベースを構築できないといった問題があります。
そのため、先にメール認証を作成しようと思っているのですがいかがでしょうか？

時間的に次のミーティングまでの完成は難しいと思っています。
APIごとに分担したいので、一度マージさせ、メール認証(送受信)が完成しマージした後にリファクタ要件として行うのがベストであると思っています。

2024-08-17 06:39 UTC, Lit-innosence commented on src/main.rs
> +}
リクエストのJSONデータを受け取る処理は確かにそうですね。
把握しました。

2024-08-17 06:40 UTC, Lit-innosence commented on src/db_connector.rs
>              .get_result(conn)
ありがとうございます。

2024-08-17 06:53 UTC, Lit-innosence commented
メール認証で変更されるファイルも多いと思うので、コンフリクトを避けるためにもそれが良いと思います。

2024-08-18 01:49 UTC, Dot-P commented
検討事項
- student_pairにおいて重複したデータを許してしまうこと
- コード分割 https://github.com/Lit-innosence/tus_yuurikai_system/issues/9#issue-2467313566

2024-08-18 01:51 UTC, merged